import { Router } from 'express';
import { authRoutes } from './auth.routes';
import { vehicleRoutes } from './vehicles.routes';
import { leadRoutes } from './leads.routes';
import { tradeInRoutes } from './trade-in.routes';
import { financingApplicationsRoutes } from './financing-applications.routes';
import { orderRoutes } from './orders.routes';
import { quotationRoutes } from './quotations.routes';
import { workshopRoutes } from './workshop.routes';
import { partsRoutes } from './parts.routes';
import { financingRoutes } from './financing.routes';
import { customerRoutes } from './customers.routes';
import { dealerRoutes } from './dealers.routes';
import { settingRoutes } from './settings.routes';
import { contentRoutes } from './content.routes';
import { servicesMenuRoutes } from './services-menu.routes';
import { mediaRoutes } from './media.routes';
import { analyticsRoutes } from './analytics.routes';
import { userRoutes } from './users.routes';
import { promotionRoutes } from './promotions.routes';
import { reviewRoutes } from './reviews.routes';
import { messageRoutes } from './messages.routes';
import { newsRoutes } from './news.routes';
import { testDriveRoutes } from './test-drives.routes';
import { serviceBookingRoutes } from './service-bookings.routes';
import { showroomVisitRoutes } from './showroom-visits.routes';
import { handoverRoutes } from './handover.routes';
import { agreementRoutes } from './agreement.routes';
import { staffSignatureRoutes } from './staff-signature.routes';
import { csiSurveyRoutes } from './csi-survey.routes';
import { newsletterRoutes } from './newsletter.routes';
import { redirectRoutes } from './redirects.routes';
import { searchRoutes } from './search.routes';
import { crmRoutes } from './crm.routes';
import { paymentRoutes } from './payments.routes';
import { publicRoutes } from './public.routes';
import { uploadRoutes } from './upload.routes';
import { commissionRoutes } from './commission.routes';
import { slaRoutes } from './sla.routes';
import { warrantyRoutes } from './warranty.routes';
import { serviceCheckInRoutes } from './service-check-in.routes';
import { customerSatisfactionRoutes } from './customer-satisfaction.routes';
import { dashboardRoutes } from './dashboard.routes';
import { auditRoutes } from './audit.routes';
import { complaintRoutes } from './complaints.routes';
import { repeatPurchaseRoutes } from './repeat-purchase.routes';
import { syncRoutes } from './sync.routes';
import { chatbotRoutes } from './chatbot.routes';
import { notificationRoutes } from './notifications.routes';
import { partRequestRoutes } from './parts-requests.routes';
import { categoriesRoutes } from './categories.routes';
import { adminContentRoutes } from './admin-content.routes';
import { rolePermissionsRoutes } from './role-permissions.routes';
import { showroomVisitAdminRoutes } from './showroom-visits-admin.routes';
import { vehicleConfigRoutes } from './vehicle-config.routes';

const router = Router();

router.use('/leads', leadRoutes);
router.use('/auth', authRoutes);
router.use('/vehicles', vehicleRoutes);
router.use('/trade-in', tradeInRoutes);
router.use('/financing-applications', financingApplicationsRoutes);
router.use('/orders', orderRoutes);
router.use('/quotations', quotationRoutes);
router.use('/commission', commissionRoutes);
router.use('/admin/workshop', workshopRoutes);
router.use('/parts', partsRoutes);
router.use('/financing', financingRoutes);
router.use('/customers', customerRoutes);
router.use('/dealers', dealerRoutes);
router.use('/settings', settingRoutes);
router.use('/content', contentRoutes);
router.use('/services-menu', servicesMenuRoutes);
router.use('/media', mediaRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/admin/users', userRoutes);
router.use('/promotions', promotionRoutes);
router.use('/reviews', reviewRoutes);
router.use('/messages', messageRoutes);
router.use('/news', newsRoutes);
router.use('/test-drives', testDriveRoutes);
router.use('/service-bookings', serviceBookingRoutes);
router.use('/visit', showroomVisitRoutes);
router.use('/handover', handoverRoutes);
router.use('/agreement', agreementRoutes);
router.use('/staff-signature', staffSignatureRoutes);
router.use('/csi-survey', csiSurveyRoutes);
router.use('/newsletter', newsletterRoutes);
router.use('/redirects', redirectRoutes);
router.use('/search', searchRoutes);
router.use('/crm', crmRoutes);
router.use('/payments', paymentRoutes);
router.use('/public', publicRoutes);
router.use('/upload', uploadRoutes);
router.use('/sla', slaRoutes);
router.use('/warranty', warrantyRoutes);
router.use('/service-check-in', serviceCheckInRoutes);
router.use('/customer-satisfaction', customerSatisfactionRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/audit', auditRoutes);
router.use('/complaints', complaintRoutes);
router.use('/repeat-purchase', repeatPurchaseRoutes);
router.use('/sync', syncRoutes);
router.use('/chatbot', chatbotRoutes);
router.use('/notifications', notificationRoutes);
router.use('/admin/parts-requests', partRequestRoutes);
router.use('/admin', categoriesRoutes);
router.use('/admin', adminContentRoutes);
router.use('/admin/role-permissions', rolePermissionsRoutes);
router.use('/admin/showroom-visits', showroomVisitAdminRoutes);
router.use('/admin', vehicleConfigRoutes);

export { router as routes };
