import { Router, Request, Response } from 'express';
import { requireAdminApiSession, requirePermission } from '../middleware/auth';
import { generateDashboardReportPdf, DashboardReportSection } from '../services/pdf/dashboardReport.pdf';
import { slugify } from '../utils/formatting';

const router = Router();

const MAX_SECTIONS = 30;
const MAX_ROWS_PER_SECTION = 500;
const MAX_STRING_LENGTH = 500;

function clampString(value: unknown): string {
  return String(value ?? '').slice(0, MAX_STRING_LENGTH);
}

// Validates + normalizes the client-supplied report body into
// DashboardReportSection[], rejecting anything malformed rather than trying
// to render garbage into a PDF. Every admin dashboard's export button posts
// here, so the shape of what a section can be stays deliberately small
// (stats pairs or a table) — see dashboardReport.pdf.ts.
function parseSections(input: unknown): DashboardReportSection[] | null {
  if (!Array.isArray(input) || input.length === 0 || input.length > MAX_SECTIONS) return null;
  const sections: DashboardReportSection[] = [];
  for (const raw of input) {
    if (!raw || typeof raw !== 'object') return null;
    const title = clampString((raw as any).title);
    if (!title) return null;
    if ((raw as any).kind === 'stats') {
      const items = (raw as any).items;
      if (!Array.isArray(items)) return null;
      sections.push({
        kind: 'stats',
        title,
        items: items.slice(0, MAX_ROWS_PER_SECTION).map((item: any) => ({
          label: clampString(item?.label),
          value: clampString(item?.value),
        })),
      });
      continue;
    }
    if ((raw as any).kind === 'table') {
      const columns = (raw as any).columns;
      const rows = (raw as any).rows;
      if (!Array.isArray(columns) || !Array.isArray(rows)) return null;
      sections.push({
        kind: 'table',
        title,
        columns: columns.slice(0, 12).map(clampString),
        rows: rows.slice(0, MAX_ROWS_PER_SECTION).map((row: any) =>
          (Array.isArray(row) ? row : []).slice(0, 12).map((cell: any) => clampString(cell))
        ),
        note: (raw as any).note ? clampString((raw as any).note) : undefined,
      });
      continue;
    }
    return null;
  }
  return sections;
}

// POST /api/reports/dashboard-pdf — renders any admin dashboard's on-screen
// data into a branded PDF (same letterhead as the sales documents). The
// caller's name/role always come from their own session, never the request
// body, so a report can't be spoofed as having been "generated by" someone
// else.
router.post('/dashboard-pdf', requireAdminApiSession, requirePermission('canExportReports'), async (req: Request, res: Response) => {
  try {
    const title = clampString(req.body?.title) || 'Dashboard Report';
    const subtitle = req.body?.subtitle ? clampString(req.body.subtitle) : undefined;
    const sections = parseSections(req.body?.sections);
    if (!sections) {
      res.status(400).json({ error: 'Invalid report sections' });
      return;
    }

    const user = req.adminSession!.user;
    const pdf = await generateDashboardReportPdf({
      title,
      subtitle,
      generatedByName: user.name,
      generatedByRole: user.role,
      sections,
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${slugify(title)}-${new Date().toISOString().slice(0, 10)}.pdf"`);
    res.send(pdf);
  } catch (error) {
    console.error('Dashboard report PDF error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

export { router as reportsRoutes };
