import { getCompanyInfo } from './companyInfo';
import {
  openDocument, addPage, drawHeaderFooter, drawSectionTitle, drawTable, drawFieldTable,
  ensureSpace, saveBuffer, PDF_HEADER_CONTENT_Y, PDF_CONTENT_WIDTH, PDF_MARGIN,
  COLORS,
} from './pdfLayout';
import { formatDateTime } from '../../utils/formatting';

// Generic branded PDF for any admin dashboard — reuses the same letterhead
// (company legal name + title + footer) as the 4 sales documents, but the
// body is driven entirely by the `sections` the caller supplies (stat pairs
// and/or tables) instead of a fixed document layout, since this one function
// backs the export button on every dashboard (Analytics, CRM, Workshop BI,
// Workshop Live) rather than a single document type.

export interface DashboardReportStatsSection {
  kind: 'stats';
  title: string;
  items: Array<{ label: string; value: string }>;
}

export interface DashboardReportTableSection {
  kind: 'table';
  title: string;
  columns: string[];
  rows: Array<Array<string | number>>;
  note?: string;
}

export type DashboardReportSection = DashboardReportStatsSection | DashboardReportTableSection;

export interface DashboardReportInput {
  title: string;
  subtitle?: string;
  generatedByName: string;
  generatedByRole: string;
  sections: DashboardReportSection[];
}

// Splits PDF_CONTENT_WIDTH across N columns, giving the first column extra
// room (it usually holds a name/label, the rest hold short numbers).
function columnWidths(count: number): number[] {
  if (count <= 1) return [PDF_CONTENT_WIDTH];
  const firstWidth = Math.min(PDF_CONTENT_WIDTH * 0.34, 220);
  const rest = (PDF_CONTENT_WIDTH - firstWidth) / (count - 1);
  return [firstWidth, ...Array(count - 1).fill(rest)];
}

export async function generateDashboardReportPdf(input: DashboardReportInput): Promise<Buffer> {
  const company = await getCompanyInfo();
  const doc = await openDocument();
  let ctx = addPage(doc);
  ctx = await drawHeaderFooter(ctx, input.title, company);
  ctx.y = PDF_HEADER_CONTENT_Y;

  if (input.subtitle) {
    ctx.page.drawText(input.subtitle, { x: PDF_MARGIN, y: ctx.y, size: 10, font: ctx.font, color: COLORS.gray });
    ctx.y -= 16;
  }
  const meta = `Generated by ${input.generatedByName} (${input.generatedByRole}) on ${formatDateTime(new Date())}`;
  ctx.page.drawText(meta, { x: PDF_MARGIN, y: ctx.y, size: 8, font: ctx.italic, color: COLORS.gray });
  ctx.y -= 24;

  for (const section of input.sections) {
    const nextPage = ensureSpace(ctx, 40);
    // ensureSpace() only breaks the page — it doesn't know about the
    // letterhead, so a section that starts a new page has to get its own
    // header/footer drawn here. A section whose own table/field-list is long
    // enough to overflow mid-section triggers a further internal ensureSpace()
    // inside drawTable()/drawFieldTable() that page-breaks without a
    // header/footer — the same pre-existing limitation the sales-document
    // generators already have, not something new to this report.
    if (nextPage.page !== ctx.page) {
      nextPage = await drawHeaderFooter(nextPage, undefined, company);
      nextPage.y = PDF_HEADER_CONTENT_Y;
    }
    ctx = nextPage;
    drawSectionTitle(ctx, section.title);

    if (section.kind === 'stats') {
      if (section.items.length === 0) {
        ctx.page.drawText('No data.', { x: PDF_MARGIN, y: ctx.y, size: 9, font: ctx.italic, color: COLORS.gray });
        ctx.y -= 18;
        continue;
      }
      ctx = drawFieldTable(ctx, section.items.map((item) => [item.label, item.value] as [string, string]));
      ctx.y -= 12;
      continue;
    }

    if (section.rows.length === 0) {
      ctx.page.drawText('No data.', { x: PDF_MARGIN, y: ctx.y, size: 9, font: ctx.italic, color: COLORS.gray });
      ctx.y -= 18;
      continue;
    }
    drawTable(ctx, section.columns, section.rows, columnWidths(section.columns.length));
    ctx.y -= 12;
    if (section.note) {
      ctx = ensureSpace(ctx, 16);
      ctx.page.drawText(section.note, { x: PDF_MARGIN, y: ctx.y, size: 8, font: ctx.italic, color: COLORS.gray });
      ctx.y -= 16;
    }
  }

  return saveBuffer(doc);
}
