import { AdminRole, AdminPermissions } from '../types/auth.types';

// Default role-based permissions — identical to the hardcoded presets
// in admin/lib/auth/types.ts. The DB overrides (RolePermissionOverride
// model) are layered on top at runtime by getEffectivePermissions().
export const ROLE_PERMISSIONS: Record<AdminRole, AdminPermissions> = {
  [AdminRole.SUPER_ADMIN]: {
    canManageContent: true, canViewContent: true,
    canManageVehicles: true, canViewVehicles: true,
    canManageTestDrives: true, canViewTestDrives: true,
    canManageQuotations: true, canViewQuotations: true, canCountersignAgreements: true,
    canManageDealers: true, canViewDealers: true,
    canManageServiceBookings: true, canViewServiceBookings: true, canManageService: true,
    canManageSpareParts: true, canViewSpareParts: true,
    canManagePromotions: true, canViewPromotions: true,
    canModerateReviews: true, canViewReviews: true,
    canManageNews: true, canViewNews: true,
    canManageMessages: true, canViewMessages: true,
    canViewAnalytics: true, canExportReports: true, canViewReports: true,
    canViewExecutiveDashboards: true,
    canManageUsers: true, canViewUsers: true,
    canManageSettings: true, canViewSettings: true,
    canViewJobCards: true, canManageJobCards: true,
    canManageBays: true, canManageTechnicians: true, canPerformQC: true,
    canManagePartsIssue: true, canApproveWarrantyClaims: true,
  },
  [AdminRole.ADMIN]: {
    canManageContent: true, canViewContent: true,
    canManageVehicles: true, canViewVehicles: true,
    canManageTestDrives: true, canViewTestDrives: true,
    canManageQuotations: true, canViewQuotations: true, canCountersignAgreements: true,
    canManageDealers: true, canViewDealers: true,
    canManageServiceBookings: true, canViewServiceBookings: true, canManageService: true,
    canManageSpareParts: true, canViewSpareParts: true,
    canManagePromotions: true, canViewPromotions: true,
    canModerateReviews: true, canViewReviews: true,
    canManageNews: true, canViewNews: true,
    canManageMessages: true, canViewMessages: true,
    canViewAnalytics: true, canExportReports: true, canViewReports: true,
    canViewExecutiveDashboards: true,
    canManageUsers: true, canViewUsers: true,
    canManageSettings: true, canViewSettings: true,
    canViewJobCards: true, canManageJobCards: true,
    canManageBays: true, canManageTechnicians: true, canPerformQC: true,
    canManagePartsIssue: true, canApproveWarrantyClaims: true,
  },
  [AdminRole.MANAGER]: {
    canManageContent: true, canViewContent: true,
    canManageVehicles: true, canViewVehicles: true,
    canManageTestDrives: true, canViewTestDrives: true,
    canManageQuotations: true, canViewQuotations: true, canCountersignAgreements: false,
    canManageDealers: false, canViewDealers: true,
    canManageServiceBookings: true, canViewServiceBookings: true, canManageService: true,
    canManageSpareParts: true, canViewSpareParts: true,
    canManagePromotions: true, canViewPromotions: true,
    canModerateReviews: true, canViewReviews: true,
    canManageNews: true, canViewNews: true,
    canManageMessages: true, canViewMessages: true,
    canViewAnalytics: true, canExportReports: true, canViewReports: true,
    canViewExecutiveDashboards: true,
    canManageUsers: false, canViewUsers: true,
    canManageSettings: false, canViewSettings: true,
    canViewJobCards: true, canManageJobCards: true,
    canManageBays: true, canManageTechnicians: true, canPerformQC: true,
    canManagePartsIssue: true, canApproveWarrantyClaims: true,
  },
  [AdminRole.SALES]: {
    canManageContent: false, canViewContent: true,
    canManageVehicles: true, canViewVehicles: true,
    canManageTestDrives: true, canViewTestDrives: true,
    canManageQuotations: true, canViewQuotations: true, canCountersignAgreements: false,
    canManageDealers: false, canViewDealers: true,
    canManageServiceBookings: false, canViewServiceBookings: false, canManageService: false,
    canManageSpareParts: false, canViewSpareParts: true,
    canManagePromotions: false, canViewPromotions: true,
    canModerateReviews: false, canViewReviews: true,
    canManageNews: false, canViewNews: true,
    canManageMessages: true, canViewMessages: true,
    canViewAnalytics: true, canExportReports: false, canViewReports: true,
    canViewExecutiveDashboards: false,
    canManageUsers: false, canViewUsers: false,
    canManageSettings: false, canViewSettings: false,
    canViewJobCards: false, canManageJobCards: false,
    canManageBays: false, canManageTechnicians: false, canPerformQC: false,
    canManagePartsIssue: false, canApproveWarrantyClaims: false,
  },
  [AdminRole.SERVICE]: {
    canManageContent: false, canViewContent: false,
    canManageVehicles: false, canViewVehicles: true,
    canManageTestDrives: false, canViewTestDrives: false,
    canManageQuotations: false, canViewQuotations: false, canCountersignAgreements: false,
    canManageDealers: false, canViewDealers: true,
    canManageServiceBookings: true, canViewServiceBookings: true, canManageService: true,
    canManageSpareParts: true, canViewSpareParts: true,
    canManagePromotions: false, canViewPromotions: false,
    canModerateReviews: false, canViewReviews: false,
    canManageNews: false, canViewNews: false,
    canManageMessages: true, canViewMessages: true,
    canViewAnalytics: true, canExportReports: false, canViewReports: true,
    canViewExecutiveDashboards: false,
    canManageUsers: false, canViewUsers: false,
    canManageSettings: false, canViewSettings: false,
    canViewJobCards: true, canManageJobCards: true,
    canManageBays: false, canManageTechnicians: false, canPerformQC: false,
    canManagePartsIssue: false, canApproveWarrantyClaims: false,
  },
  [AdminRole.MARKETING]: {
    canManageContent: true, canViewContent: true,
    canManageVehicles: false, canViewVehicles: true,
    canManageTestDrives: false, canViewTestDrives: true,
    canManageQuotations: false, canViewQuotations: true, canCountersignAgreements: false,
    canManageDealers: false, canViewDealers: true,
    canManageServiceBookings: false, canViewServiceBookings: false, canManageService: false,
    canManageSpareParts: false, canViewSpareParts: false,
    canManagePromotions: true, canViewPromotions: true,
    canModerateReviews: true, canViewReviews: true,
    canManageNews: true, canViewNews: true,
    canManageMessages: true, canViewMessages: true,
    canViewAnalytics: true, canExportReports: true, canViewReports: true,
    canViewExecutiveDashboards: false,
    canManageUsers: false, canViewUsers: false,
    canManageSettings: false, canViewSettings: false,
    canViewJobCards: false, canManageJobCards: false,
    canManageBays: false, canManageTechnicians: false, canPerformQC: false,
    canManagePartsIssue: false, canApproveWarrantyClaims: false,
  },
  [AdminRole.SERVICE_ADVISOR]: {
    canManageContent: false, canViewContent: false,
    canManageVehicles: false, canViewVehicles: true,
    canManageTestDrives: false, canViewTestDrives: false,
    canManageQuotations: false, canViewQuotations: false, canCountersignAgreements: false,
    canManageDealers: false, canViewDealers: true,
    canManageServiceBookings: true, canViewServiceBookings: true, canManageService: true,
    canManageSpareParts: false, canViewSpareParts: true,
    canManagePromotions: false, canViewPromotions: false,
    canModerateReviews: false, canViewReviews: false,
    canManageNews: false, canViewNews: false,
    canManageMessages: true, canViewMessages: true,
    canViewAnalytics: true, canExportReports: false, canViewReports: true,
    canViewExecutiveDashboards: false,
    canManageUsers: false, canViewUsers: false,
    canManageSettings: false, canViewSettings: false,
    canViewJobCards: true, canManageJobCards: true,
    canManageBays: false, canManageTechnicians: false, canPerformQC: false,
    canManagePartsIssue: false, canApproveWarrantyClaims: false,
  },
  [AdminRole.SERVICE_MANAGER]: {
    canManageContent: false, canViewContent: true,
    canManageVehicles: false, canViewVehicles: true,
    canManageTestDrives: false, canViewTestDrives: true,
    canManageQuotations: false, canViewQuotations: true, canCountersignAgreements: false,
    canManageDealers: false, canViewDealers: true,
    canManageServiceBookings: true, canViewServiceBookings: true, canManageService: true,
    canManageSpareParts: true, canViewSpareParts: true,
    canManagePromotions: false, canViewPromotions: false,
    canModerateReviews: false, canViewReviews: false,
    canManageNews: false, canViewNews: false,
    canManageMessages: true, canViewMessages: true,
    canViewAnalytics: true, canExportReports: true, canViewReports: true,
    canViewExecutiveDashboards: true,
    canManageUsers: false, canViewUsers: false,
    canManageSettings: false, canViewSettings: false,
    canViewJobCards: true, canManageJobCards: true,
    canManageBays: true, canManageTechnicians: true, canPerformQC: true,
    canManagePartsIssue: true, canApproveWarrantyClaims: true,
  },
  [AdminRole.SALES_REPRESENTATIVE]: {
    canManageContent: false, canViewContent: true,
    canManageVehicles: false, canViewVehicles: true,
    canManageTestDrives: true, canViewTestDrives: true,
    canManageQuotations: true, canViewQuotations: true, canCountersignAgreements: false,
    canManageDealers: false, canViewDealers: true,
    canManageServiceBookings: false, canViewServiceBookings: false, canManageService: false,
    canManageSpareParts: false, canViewSpareParts: true,
    canManagePromotions: false, canViewPromotions: true,
    canModerateReviews: false, canViewReviews: true,
    canManageNews: false, canViewNews: true,
    canManageMessages: true, canViewMessages: true,
    canViewAnalytics: true, canExportReports: false, canViewReports: true,
    canViewExecutiveDashboards: false,
    canManageUsers: false, canViewUsers: false,
    canManageSettings: false, canViewSettings: false,
    canViewJobCards: false, canManageJobCards: false,
    canManageBays: false, canManageTechnicians: false, canPerformQC: false,
    canManagePartsIssue: false, canApproveWarrantyClaims: false,
  },
  [AdminRole.SALES_MANAGER]: {
    canManageContent: false, canViewContent: true,
    canManageVehicles: false, canViewVehicles: true,
    canManageTestDrives: true, canViewTestDrives: true,
    canManageQuotations: true, canViewQuotations: true, canCountersignAgreements: true,
    canManageDealers: false, canViewDealers: true,
    canManageServiceBookings: false, canViewServiceBookings: false, canManageService: false,
    canManageSpareParts: false, canViewSpareParts: true,
    canManagePromotions: false, canViewPromotions: true,
    canModerateReviews: false, canViewReviews: true,
    canManageNews: false, canViewNews: true,
    canManageMessages: true, canViewMessages: true,
    canViewAnalytics: true, canExportReports: true, canViewReports: true,
    canViewExecutiveDashboards: true,
    canManageUsers: false, canViewUsers: false,
    canManageSettings: false, canViewSettings: false,
    canViewJobCards: false, canManageJobCards: false,
    canManageBays: false, canManageTechnicians: false, canPerformQC: false,
    canManagePartsIssue: false, canApproveWarrantyClaims: false,
  },
  [AdminRole.WORKSHOP_MANAGER]: {
    canManageContent: false, canViewContent: false,
    canManageVehicles: false, canViewVehicles: true,
    canManageTestDrives: false, canViewTestDrives: false,
    canManageQuotations: false, canViewQuotations: false, canCountersignAgreements: false,
    canManageDealers: false, canViewDealers: true,
    canManageServiceBookings: true, canViewServiceBookings: true, canManageService: true,
    canManageSpareParts: false, canViewSpareParts: true,
    canManagePromotions: false, canViewPromotions: false,
    canModerateReviews: false, canViewReviews: false,
    canManageNews: false, canViewNews: false,
    canManageMessages: true, canViewMessages: true,
    canViewAnalytics: true, canExportReports: false, canViewReports: true,
    canViewExecutiveDashboards: true,
    canManageUsers: false, canViewUsers: false,
    canManageSettings: false, canViewSettings: false,
    canViewJobCards: true, canManageJobCards: true,
    canManageBays: true, canManageTechnicians: true, canPerformQC: true,
    canManagePartsIssue: true, canApproveWarrantyClaims: false,
  },
  [AdminRole.AFTER_SALES_MANAGER]: {
    canManageContent: false, canViewContent: false,
    canManageVehicles: false, canViewVehicles: true,
    canManageTestDrives: false, canViewTestDrives: false,
    canManageQuotations: false, canViewQuotations: false, canCountersignAgreements: false,
    canManageDealers: false, canViewDealers: true,
    canManageServiceBookings: true, canViewServiceBookings: true, canManageService: true,
    canManageSpareParts: true, canViewSpareParts: true,
    canManagePromotions: false, canViewPromotions: false,
    canModerateReviews: false, canViewReviews: false,
    canManageNews: false, canViewNews: false,
    canManageMessages: true, canViewMessages: true,
    canViewAnalytics: true, canExportReports: true, canViewReports: true,
    canViewExecutiveDashboards: true,
    canManageUsers: false, canViewUsers: false,
    canManageSettings: false, canViewSettings: false,
    canViewJobCards: true, canManageJobCards: true,
    canManageBays: true, canManageTechnicians: true, canPerformQC: true,
    canManagePartsIssue: true, canApproveWarrantyClaims: true,
  },
  [AdminRole.GM_GEELY]: {
    canManageContent: false, canViewContent: true,
    canManageVehicles: false, canViewVehicles: true,
    canManageTestDrives: false, canViewTestDrives: true,
    canManageQuotations: true, canViewQuotations: true, canCountersignAgreements: false,
    canManageDealers: true, canViewDealers: true,
    canManageServiceBookings: false, canViewServiceBookings: true, canManageService: false,
    canManageSpareParts: false, canViewSpareParts: true,
    canManagePromotions: false, canViewPromotions: true,
    canModerateReviews: false, canViewReviews: true,
    canManageNews: false, canViewNews: true,
    canManageMessages: false, canViewMessages: true,
    canViewAnalytics: true, canExportReports: true, canViewReports: true,
    canViewExecutiveDashboards: true,
    canManageUsers: false, canViewUsers: true,
    canManageSettings: false, canViewSettings: true,
    canViewJobCards: true, canManageJobCards: false,
    canManageBays: false, canManageTechnicians: false, canPerformQC: false,
    canManagePartsIssue: false, canApproveWarrantyClaims: true,
  },
  [AdminRole.CUSTOMER]: {
    canManageContent: false, canViewContent: false,
    canManageVehicles: false, canViewVehicles: false,
    canManageTestDrives: false, canViewTestDrives: false,
    canManageQuotations: false, canViewQuotations: false, canCountersignAgreements: false,
    canManageDealers: false, canViewDealers: false,
    canManageServiceBookings: false, canViewServiceBookings: false, canManageService: false,
    canManageSpareParts: false, canViewSpareParts: false,
    canManagePromotions: false, canViewPromotions: false,
    canModerateReviews: false, canViewReviews: false,
    canManageNews: false, canViewNews: false,
    canManageMessages: false, canViewMessages: false,
    canViewAnalytics: false, canExportReports: false, canViewReports: false,
    canViewExecutiveDashboards: false,
    canManageUsers: false, canViewUsers: false,
    canManageSettings: false, canViewSettings: false,
    canViewJobCards: false, canManageJobCards: false,
    canManageBays: false, canManageTechnicians: false, canPerformQC: false,
    canManagePartsIssue: false, canApproveWarrantyClaims: false,
  },
  [AdminRole.DEALER]: {
    canManageContent: false, canViewContent: false,
    canManageVehicles: false, canViewVehicles: false,
    canManageTestDrives: false, canViewTestDrives: false,
    canManageQuotations: false, canViewQuotations: false, canCountersignAgreements: false,
    canManageDealers: false, canViewDealers: false,
    canManageServiceBookings: false, canViewServiceBookings: false, canManageService: false,
    canManageSpareParts: false, canViewSpareParts: false,
    canManagePromotions: false, canViewPromotions: false,
    canModerateReviews: false, canViewReviews: false,
    canManageNews: false, canViewNews: false,
    canManageMessages: false, canViewMessages: false,
    canViewAnalytics: false, canExportReports: false, canViewReports: false,
    canViewExecutiveDashboards: false,
    canManageUsers: false, canViewUsers: false,
    canManageSettings: false, canViewSettings: false,
    canViewJobCards: false, canManageJobCards: false,
    canManageBays: false, canManageTechnicians: false, canPerformQC: false,
    canManagePartsIssue: false, canApproveWarrantyClaims: false,
  },
};
